---
- hosts: all
  connection: local
  gather_facts: no
  vars:
  tasks:
  - name: get log
    ios_command:
      commands: "{{ command_list }}"
    register: result

  - name: debug
    debug:
      var: result.stdout_lines

  - name: write log files
    copy:
      content: "{{ result.stdout_lines }}"
      dest: "/var/lib/awx/projects/log/{{ inventory_hostname }}_{{ lookup('pipe','date +%Y%m%d_%H%M%S') }}.log"